app/__init__.py
from flask import Flask

from .main.routes import main
from .extentions import mongo

def create_app():
    app = Flask(__name__)
    app.secret_key = 'secret'
    app.config['MONGO_URI'] = 'mongodb+srv://dmn:95241243@cluster0.h01fl.mongodb.net/mydb?retryWrites=true&w=majority'
    mongo.init_app(app)

    app.register_blueprint(main)

    return app

app/main/routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for
from app.extentions import check_user_in_collection, mongo

main = Blueprint('main', __name__)

@main.route('/')
def index():
    user = ''
    if 'user' in session:
        user = session['user']

    return render_template('index.html', user=user)

@main.route('/add_user', methods=['POST'])
def add_user():
    users_collection = mongo.db.users
    user = request.form.get('add-user')
    session['user'] = user
    isUser = check_user_in_collection(user)

    if (isUser is not True):
        users_collection.insert_one({'name': user})
    
    return redirect(url_for('main.index'))

@main.route('/users', methods=['GET'])
def get_users():
    users_collection = mongo.db.users
    users = users_collection.find()

    return render_template('users.html', users=users)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="container">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% block body %}
<form action="{{ url_for('main.add_user') }}" method="post">
    <input type="text" name="add-user">
    <button>Привітатись</button>
</form>
<a href="{{ url_for('main.get_users') }}">Переглянути список користувачів</a>
<div class="response">
    <h2>{{ user }}</h2>
</div>

{% endblock %}

app/templates/users.html
{% extends 'base.html' %}

{% block body %}

<div class="users-list">
    <a href="/">Повернутися</a>
    <ul>
        {% for user in users %}
            <li>{{user.name}}</li>
        {% endfor %}
    </ul>
</div>

{% endblock %}